# Exploratory Data Analysis
Understanding the dataset to explore how the data is present in the database and if there is a need of creating some aggregated tables that can help with:

- Vendor selection for profitability  
- Product Pricing Optimization

In [3]:
import pandas as pd
import sqlite3

# creating database connection
conn = sqlite3.connect('inventory.db')

# checking tables present in the database
tables = pd.read_sql_query("  select * from sqlite_master where type ='table' ",conn)
tables

for table in tables['name']:
    print('-'*50, f'{table}','-'*50)
    print('count of records: ', pd.read_sql(f"select count(*) as count from {table}",conn)['count'].values[0])
    print(pd.read_sql(f"select * from {table} limit 5",conn))

-------------------------------------------------- begin_inventory --------------------------------------------------
count of records:  206529
         InventoryId  Store          City  Brand                  Description  \
0  1_HARDERSFIELD_58      1  HARDERSFIELD     58  Gekkeikan Black & Gold Sake
1  1_HARDERSFIELD_60      1  HARDERSFIELD     60       Canadian Club 1858 VAP
2  1_HARDERSFIELD_62      1  HARDERSFIELD     62     Herradura Silver Tequila
3  1_HARDERSFIELD_63      1  HARDERSFIELD     63   Herradura Reposado Tequila
4  1_HARDERSFIELD_72      1  HARDERSFIELD     72         No. 3 London Dry Gin

    Size  onHand  Price   startDate
0  750mL       8  12.99  2024-01-01
1  750mL       7  10.99  2024-01-01
2  750mL       6  36.99  2024-01-01
3  750mL       3  38.99  2024-01-01
4  750mL       6  34.99  2024-01-01
-------------------------------------------------- end_inventory --------------------------------------------------
count of records:  224489
         InventoryId  Store          City  Brand                  Description  \
0  1_HARDERSFIELD_58      1  HARDERSFIELD     58  Gekkeikan Black & Gold Sake
1  1_HARDERSFIELD_62      1  HARDERSFIELD     62     Herradura Silver Tequila
2  1_HARDERSFIELD_63      1  HARDERSFIELD     63   Herradura Reposado Tequila
3  1_HARDERSFIELD_72      1  HARDERSFIELD     72         No. 3 London Dry Gin
4  1_HARDERSFIELD_75      1  HARDERSFIELD     75    Three Olives Tomato Vodka

    Size  onHand  Price     endDate
0  750mL      11  12.99  2024-12-31
1  750mL       7  36.99  2024-12-31
2  750mL       7  38.99  2024-12-31
3  750mL       4  34.99  2024-12-31
4  750mL       7  14.99  2024-12-31
-------------------------------------------------- purchases --------------------------------------------------
count of records:  2372474
           InventoryId  Store  Brand                   Description   Size  \
0    69_MOUNTMEND_8412     69   8412     Tequila Ocho Plata Fresno  750mL
1     30_CULCHETH_5255     30   5255  TGI Fridays Ultimte Mudslide  1.75L
2    34_PITMERDEN_5215     34   5215  TGI Fridays Long Island Iced  1.75L
3  1_HARDERSFIELD_5255      1   5255  TGI Fridays Ultimte Mudslide  1.75L
4    76_DONCASTER_2034     76   2034     Glendalough Double Barrel  750mL

   VendorNumber                   VendorName  PONumber      PODate  \
0           105  ALTAMAR BRANDS LLC               8124  2023-12-21
1          4466  AMERICAN VINTAGE BEVERAGE        8137  2023-12-22
2          4466  AMERICAN VINTAGE BEVERAGE        8137  2023-12-22
3          4466  AMERICAN VINTAGE BEVERAGE        8137  2023-12-22
4           388  ATLANTIC IMPORTING COMPANY       8169  2023-12-24

  ReceivingDate InvoiceDate     PayDate  PurchasePrice  Quantity  Dollars  \
0    2024-01-02  2024-01-04  2024-02-16          35.71         6   214.26
1    2024-01-01  2024-01-07  2024-02-21           9.35         4    37.40
2    2024-01-02  2024-01-07  2024-02-21           9.41         5    47.05
3    2024-01-01  2024-01-07  2024-02-21           9.35         6    56.10
4    2024-01-02  2024-01-09  2024-02-16          21.32         5   106.60

   Classification
0               1
1               1
2               1
3               1
4               1
-------------------------------------------------- purchase_prices --------------------------------------------------
count of records:  12261
   Brand                  Description  Price   Size Volume  Classification  \
0     58  Gekkeikan Black & Gold Sake  12.99  750mL    750               1
1     62     Herradura Silver Tequila  36.99  750mL    750               1
2     63   Herradura Reposado Tequila  38.99  750mL    750               1
3     72         No. 3 London Dry Gin  34.99  750mL    750               1
4     75    Three Olives Tomato Vodka  14.99  750mL    750               1

   PurchasePrice  VendorNumber                   VendorName
0           9.28          8320  SHAW ROSS INT L IMP LTD
1          28.67          1128  BROWN-FORMAN CORP
2          30.46          1128  BROWN-FORMAN CORP
3          26.11          9165  ULTRA BEVERAGE COMPANY LLP
4          10.94          7245  PROXIMO SPIRITS INC.
-------------------------------------------------- sales --------------------------------------------------
count of records:  12825363
           InventoryId  Store  Brand                 Description        Size  \
0  1_HARDERSFIELD_1004      1   1004  Jim Beam w/2 Rocks Glasses       750mL
1  1_HARDERSFIELD_1004      1   1004  Jim Beam w/2 Rocks Glasses       750mL
2  1_HARDERSFIELD_1004      1   1004  Jim Beam w/2 Rocks Glasses       750mL
3  1_HARDERSFIELD_1004      1   1004  Jim Beam w/2 Rocks Glasses       750mL
4  1_HARDERSFIELD_1005      1   1005     Maker's Mark Combo Pack  375mL 2 Pk

   SalesQuantity  SalesDollars  SalesPrice   SalesDate  Volume  \
0              1         16.49       16.49  2024-01-01   750.0
1              2         32.98       16.49  2024-01-02   750.0
2              1         16.49       16.49  2024-01-03   750.0
3              1         14.49       14.49  2024-01-08   750.0
4              2         69.98       34.99  2024-01-09   375.0

   Classification  ExciseTax  VendorNo                   VendorName
0               1       0.79     12546  JIM BEAM BRANDS COMPANY
1               1       1.57     12546  JIM BEAM BRANDS COMPANY
2               1       0.79     12546  JIM BEAM BRANDS COMPANY
3               1       0.79     12546  JIM BEAM BRANDS COMPANY
4               1       0.79     12546  JIM BEAM BRANDS COMPANY
-------------------------------------------------- vendor_invoice --------------------------------------------------
count of records:  5543
   VendorNumber                   VendorName InvoiceDate  PONumber  \
0           105  ALTAMAR BRANDS LLC           2024-01-04      8124
1          4466  AMERICAN VINTAGE BEVERAGE    2024-01-07      8137
2           388  ATLANTIC IMPORTING COMPANY   2024-01-09      8169
3           480  BACARDI USA INC              2024-01-12      8106
4           516  BANFI PRODUCTS CORP          2024-01-07      8170

       PODate     PayDate  Quantity    Dollars  Freight Approval
0  2023-12-21  2024-02-16         6     214.26     3.47     None
1  2023-12-22  2024-02-21        15     140.55     8.57     None
2  2023-12-24  2024-02-16         5     106.60     4.61     None
3  2023-12-20  2024-02-05     10100  137483.78  2935.20     None
4  2023-12-24  2024-02-12      1935   15527.25   429.20     None

In [6]:
purchases = pd.read_sql_query("select * from purchases where VendorNumber = 4466", conn)
purchases

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
1,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
2,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
3,38_GOULCREST_5215,38,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8207,2023-12-27,2024-01-07,2024-01-19,2024-02-26,9.41,6,56.46,1
4,59_CLAETHORPES_5215,59,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8207,2023-12-27,2024-01-05,2024-01-19,2024-02-26,9.41,6,56.46,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2187,81_PEMBROKE_5215,81,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-29,2025-01-04,2025-02-10,9.41,6,56.46,1
2188,62_KILMARNOCK_5255,62,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-28,2025-01-04,2025-02-10,9.35,5,46.75,1
2189,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-28,2025-01-04,2025-02-10,9.41,5,47.05,1
2190,6_GOULCREST_5215,6,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-31,2025-01-04,2025-02-10,9.41,6,56.46,1
2191,35_HALIVAARA_5255,35,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-27,2025-01-04,2025-02-10,9.35,5,46.75,1

In [12]:
purchases.groupby(['Brand','PurchasePrice'])[['Quantity','Dollars']].sum()

                     Quantity   Dollars
Brand PurchasePrice
3140  11.19              4640  51921.60
5215  9.41               4923  46325.43
5255  9.35               6215  58110.25

In [15]:
sales

NameError: name 'sales' is not defined